version: '3.8'

services:
    my_app:
      build:
        context: .
        dockerfile: Dockerfile
      image: app
      container_name: app
      restart: unless-stopped
      env_file:
        - .env
      ports:
        - "8080:8080"
      depends_on:
        - postgres
        - redis
      networks:
        - app-network
    postgres:
      image: postgres:14
      environment:
        POSTGRES_DB: test
        POSTGRES_USER: test
        POSTGRES_PASSWORD: test
      healthcheck:
        test: [ "CMD-SHELL", "pg_isready -d test -U test" ]
        interval: 10s
        timeout: 5s
        retries: 5
      ports:
        - "5432:5432"
      networks:
        - app-network
    redis:
      image: redis:latest
      ports:
        - "6379:6379"
      networks:
        - app-network
networks:
  app-network:
    driver: bridge